#!/bin/sh
#-
# Copyright (c) 2011 Nathan Whitehorn
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

BSDCFG_SHARE="/usr/share/bsdconfig"
. $BSDCFG_SHARE/common.subr || exit 1

windows_partition_exists()
{
	for disk in $(sysctl -n kern.disks); do
		# Skip da* as a proxy for removable media.  We could be
		# installing from a removable device with a Windows partition
		# (e.g. using Ventoy) or there # may be a removable device with
		# a Windows partition attached that is unrelated to our
		# installation.
		case $disk in
		da*)
			continue
			;;
		esac

		if gpart show $disk | egrep -q 'ms-basic-data|ntfs'; then
			return 0
		fi
	done
	return 1
}

skiputc=
if !windows_partition_exists; then
	skiputc=-s
fi

# Select timezone
chroot $BSDINSTALL_CHROOT tzsetup $skiputc

# Switch to target timezone
saved_TZ="$TZ"
TZ="${BSDINSTALL_CHROOT}/etc/localtime"
export TZ

# Set date
exec 5>&1
DATE=$(bsddialog --backtitle "$OSNAME Installer" \
	--title 'Time & Date' \
	--ok-label 'Set Date' \
	--cancel-label 'Skip' \
	--default-no \
	--date-format '%Y%m%d%H%M.%S' \
	--calendar '' 0 40 \
2>&1 1>&5) && date $DATE
exec 5>&-

# Set time
exec 5>&1
TIME=$(bsddialog --backtitle "$OSNAME Installer" \
	--title 'Time & Date' \
	--ok-label 'Set Time' \
	--cancel-label 'Skip' \
	--default-no \
	--time-format '%H%M.%S' \
	--timebox '' 0 40 \
2>&1 1>&5) && date $TIME
exec 5>&-

# Switch back
if [ -n "$saved_TZ" ]; then
	TZ="$saved_TZ"
else
	unset TZ
fi
unset saved_TZ
