# $FreeBSD$

compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-0-release-amd64
  cpu: 8
  memory: 24G
  disk: 40

task:
  name: World and kernel amd64 build and boot smoke test
  timeout_in: 120m
  install_script:
  - sh .cirrus-ci/pkg-install.sh qemu llvm12
  setup_script:
  - uname -a
  - df -m
  - pkg --version
  - pw useradd user
  - mkdir -p /usr/obj/$(pwd -P)
  - chown user:user /usr/obj/$(pwd -P)
  script:
  - su user -c "make -j$(sysctl -n hw.ncpu) TARGET_ARCH=mips64 KERNCONF=MALTA64 CROSS_TOOLCHAIN=llvm12 WITHOUT_TOOLCHAIN=yes buildworld buildkernel"
  post_script:
  - df -m
  - du -m -s /usr/obj
