# $FreeBSD$

compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-0-release-amd64
  cpu: 8
  memory: 8G
  disk: 80

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  name: World and kernel gcc9 amd64 build and boot smoke test
  timeout_in: 120m
  install_script:
  - sh .cirrus-ci/pkg-install.sh qemu-nox11
  setup_script:
  - uname -a
  - df -m
  - pkg --version
  build_script:
  - make -s -j$(sysctl -n hw.ncpu) buildworld
  - make -s -j$(sysctl -n hw.ncpu) buildkernel
  #script:
  #- sh build.sh
  release_script:
  - cd release
  - make -s -DNOPORTS -DNOSRC KERNCONF=GENERIC WITH_CLOUDWARE=yes CLOUDWARE=OCI cloudware-release
  post_script:
  - find -x / -name disk.qcow2
  - df -m
  - du -m -s /usr/obj
