env:
  CIRRUS_CLONE_DEPTH: 1

ubuntu_task:
  container:
    image: ubuntu-1604-xenial-v20171121a

  setup_script:
    - apt-get update
    - apt-get install -y bmake clang
  script:
    - bmake buildkernel
