# $FreeBSD$

freebsd_instance:
  image: freebsd-12-1-release-amd64
  cpu: 8
  memory: 24G

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  timeout_in: 90m
  install_script:
  - pkg install -y qemu-devel uefi-edk2-qemu-x86_64
  - rm -f /usr/bin/as /usr/local/bin/as
  script:
  - make -j$(sysctl -n hw.ncpu) WITHOUT_TOOLCHAIN=yes TARGET=i386 buildworld buildkernel
  package_script:
  - make WITHOUT_TOOLCHAIN=yes TARGET=i386 PKG_FORMAT=tar packages
