# $FreeBSD$

compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-1-release-amd64
  cpu: 8
  memory: 8G
  disk: 100

task:
  name: OCI image build
  environment:
    PAR_URL: ENCRYPTED[baf3e352089bf35d84bad31e5f882dee355cdb50c517a923913a971f58d5e06cd380650dff9031ee083426ebc559806b]
  timeout_in: 120m
  install_script:
  - sh .cirrus-ci/pkg-install.sh qemu-nox11 qemu-user-static curl
  setup_script:
  - uname -a
  - df -m
  - pkg --version
  ports_tree_script:
  - portsnap --interactive fetch extract
  build_script:
  - make -s -j$(sysctl -n hw.ncpu) TARGET=arm64 buildworld
  - make -s -j$(sysctl -n hw.ncpu) TARGET=arm64 buildkernel
  release_script:
  - cd release
  - make -s -DNOPORTS -DNOSRC KERNCONF=GENERIC WITH_CLOUDWARE=yes CLOUDWARE=OCI TARGET=arm64 TARGET_ARCH=aarch64 cloudware-release
  post_script:
  - find -x / -name disk.qcow2 -o -name vm.qcow2 -o -name oci.qcow2
  - curl -X PUT -T "$(make TARGET=arm64 TARGET_ARCH=aarch64 -V OBJTOP)/release/oci.qcow2" ${PAR_URL}/freebsd.main.oci.$(date +%Y%m%d_%H%M%S).qcow2
  - df -m
  - du -m -s /usr/obj
