# $FreeBSD$

freebsd_instance:
  image: freebsd-12-1-release-amd64
  cpu: 8
  memory: 24G

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  timeout_in: 120m
  install_script:
  - pkg install -y qemu-devel uefi-edk2-qemu-x86_64
  create_user_script:
  - pw useradd user
  - chown -R user:user .
  script:
  - su user -c "make -j$(sysctl -n hw.ncpu) WITHOUT_TOOLCHAIN=yes buildworld buildkernel"
  package_script:
  - su user -c "make WITHOUT_TOOLCHAIN=yes PKG_FORMAT=tar packages"
  test_script:
  - su user -c "sh tools/boot/ci-qemu-test.sh"
