# $FreeBSD$

compute_engine_instance:
  # image: freebsd-12-1-stable-amd64
  # We need a newer image to install llvm11
  image_project: freebsd-org-cloud-dev
  image: family/freebsd-12-2
  platform: freebsd
  cpu: 8
  memory: 24G
  disk: 30

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  timeout_in: 120m
  install_script:
  - pkg install -y qemu42 uefi-edk2-qemu-x86_64 llvm11
  setup_script:
  - uname -a
  - df -m
  - pw useradd user
  - mkdir -p /usr/obj/$(pwd -P)
  - chown user:user /usr/obj/$(pwd -P)
  script:
  - su user -c "make -j$(sysctl -n hw.ncpu) CROSS_TOOLCHAIN=llvm11 WITHOUT_TOOLCHAIN=yes buildworld buildkernel"
  package_script:
  - su user -c "make CROSS_TOOLCHAIN=llvm11 WITHOUT_TOOLCHAIN=yes PKG_FORMAT=tar packages"
  test_script:
  - sh tools/boot/ci-qemu-test.sh
  post_script:
  - df -m
  - du -m -s /usr/obj
