# Audio redirection
notify 0 {
	match "system"		"HDA";
	match "subsystem"	"REDIR";
	match "type"		"IN";
	match "cdev"		"dsp[0-9]+";

	action			"/usr/local/sbin/virtual_oss_cmd /dev/vdsp.ctl -R /dev/$cdev";
};

notify 0 {
	match "system"		"HDA";
	match "subsystem"	"REDIR";
	match "type"		"OUT";
	match "cdev"		"dsp[0-9]+";

	action			"/usr/local/sbin/virtual_oss_cmd /dev/vdsp.ctl -P /dev/$cdev";
};
